name: Publish to NuGet

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - build/**
      - LICENSE
      - README.md
      - Tailwind.Standalone.csproj

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Pack
        run: dotnet pack -c Release -o "${{ runner.temp }}"
          $version = Select-Xml -Path "Tailwind.Standalone.csproj" -XPath "//Version" | ForEach-Object { $_.Node.'#text' }
          if ([string]::IsNullOrWhiteSpace($version)) {
            Write-Error "Version element not found in Tailwind.Standalone.csproj. Aborting publish."
            exit 1
          }
          echo "VERSION=$version" >> $GITHUB_ENV
        shell: powershell
      - name: Publish
        run: dotnet nuget push "${{ runner.temp }}/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"
          git tag -f "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
